### ISSUE TITLE
depositing cash error

### ISSUE THREAD

**Issue by samueltuyizere** [Frankkwizera/Banking-Ussd-System#3]
hey man, i deposited cash and got this error:
`  app.models.BankUser.DoesNotExist: BankUser matching query does not exist.
`

**Comment by Frankkwizera** [comment]
You have to first register an agent with some funds to be distributed... then use agent's code while depositing. in commented the flow u can check views.py

**Comment by samueltuyizere** [comment]
coolio... thanks
